<a href="https://colab.research.google.com/github/tranduynhan02/ML_2022-2023/blob/main/Lab_5_20130346_TranDuyNhan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with **SVM** to classification tasks and compare its performance with other competitive algorithms. In general, **SVM** is one of the most popular and widely used supervised machine learning algorithms.

*   **Deadline: 23:59, 17/03/2023**



# Mount Drive

In [40]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/Study/MachineLearning/lab5'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/Study/MachineLearning/lab5


# Import libraries

In [41]:
# code
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics as metrics
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from scipy.sparse import data
from prettytable import PrettyTable

#Task 1. 
For breast cancer dataset (https://tinyurl.com/3vme8hr3) which could be loaded from datasets in sklearn as follows:

```
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
cancer = datasets.load_breast_cancer()
```

*   1.1.	Apply SVM algorithm to above dataset using linear kernel.
*   1.2.	Compare the obtained results with other competitive algorithms (Logistic Regression, Decision Tree, kNN) based on metrics: accuracy, precision, recall, f1 measures.



In [44]:
# code
cancer = datasets.load_breast_cancer()
X = cancer.data
y = cancer.target
clf = svm.SVC(kernel='linear')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix: \n", cm)
print('--------------------')
acc_svm = accuracy_score(y_test, y_pred)
print ("Accuracy: ", acc_svm)
print('--------------------')
# ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
# print("Precision: ", precision_score(y_test, y_pred, average='macro'))
# print("Recall: ", recall_score(y_test, y_pred, average='macro'))
# print("f1: ", metrics.f1_score(y_test, y_pred, average='macro'))
# print(metrics.classification_report(y_test, y_pred))
precision_svm = round((metrics.precision_score(y_test, y_pred, average = 'macro')),4)
f1_svm = round((metrics.f1_score(y_test, y_pred, average = 'macro')),4)
recall_svm = round((metrics.recall_score(y_test, y_pred, average = 'macro')),4)

Confusion Matrix: 
 [[ 60   6]
 [  1 104]]
--------------------
Accuracy:  0.9590643274853801
--------------------


In [45]:
classifier = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=1)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print('--------------------')
print ("Confusion Matrix: \n", cm)
print('--------------------')
print ("Accuracy: ", accuracy_score(y_test, y_pred))
print('--------------------')
print(metrics.classification_report(y_test, y_pred))

--------------------
Confusion Matrix: 
 [[ 58   5]
 [  7 101]]
--------------------
Accuracy:  0.9298245614035088
--------------------
              precision    recall  f1-score   support

           0       0.89      0.92      0.91        63
           1       0.95      0.94      0.94       108

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.93       171
weighted avg       0.93      0.93      0.93       171



/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [46]:
kNN = KNeighborsClassifier()
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)
kNN.fit(X_train,y_train)
y_pred = kNN.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print('--------------------')
print ("Confusion Matrix: \n", cm)
print('--------------------')
print ("Accuracy: ", accuracy_score(y_test, y_pred))
print('--------------------')
print(metrics.classification_report(y_test, y_pred))

--------------------
Confusion Matrix: 
 [[ 60   8]
 [  3 100]]
--------------------
Accuracy:  0.935672514619883
--------------------
              precision    recall  f1-score   support

           0       0.95      0.88      0.92        68
           1       0.93      0.97      0.95       103

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



#Task 2. 

*   1.1.	Perform SVM algorithm to **Iris dataset** using **linear kernel**.
*   1.2.	Compare the obtained results in 1.1 with SVM using other kernels (**Polynomial Kernel, Gaussian Kernel, Sigmoid Kernel, Radial Basis Function Kernel**). Some metrics could be used: accuracy, precision, recall, f1 measures





In [47]:
# code
iris = datasets.load_iris()
X = iris.data
y = iris.target
clf = svm.SVC(kernel='linear')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print('--------------------')
print ("Confusion Matrix: \n", cm)
print('--------------------')
acc_linear = accuracy_score(y_test, y_pred)
print ("Accuracy: ", acc_linear)
print('--------------------')
# print(metrics.classification_report(y_test, y_pred))
precision_linear = metrics.precision_score(y_test, y_pred, average='micro')
recall_linear = metrics.recall_score(y_test, y_pred, average='micro')
f1_linear = metrics.f1_score(y_test, y_pred, average='micro')

clf = svm.SVC(kernel='poly', degree=3)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_poly = round(metrics.accuracy_score(y_test, y_pred),4)
precision_poly = round(metrics.precision_score(y_test, y_pred, average='micro'),4)
recall_poly = round(metrics.recall_score(y_test, y_pred, average='micro'),4)
f1_poly = round(metrics.f1_score(y_test, y_pred, average='micro'),4)

clf = svm.SVC(kernel='sigmoid', degree=4)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_sigmoid = round(metrics.accuracy_score(y_test, y_pred),4)
precision_sigmoid = round(metrics.precision_score(y_test, y_pred, average='micro'),4)
recall_sigmoid = round(metrics.recall_score(y_test, y_pred, average='micro'),4)
f1_sigmoid = round(metrics.f1_score(y_test, y_pred, average='micro'),4)

clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_rbf = round(metrics.accuracy_score(y_test, y_pred),4)
precision_rbf = round(metrics.precision_score(y_test, y_pred, average='micro'),4)
recall_rbf = round(metrics.recall_score(y_test, y_pred, average='micro'),4)
f1_rbf = round(metrics.f1_score(y_test, y_pred, average='micro'),4)

t = PrettyTable(['','acc','precision','recall','f1'])
t.add_row(['linear',acc_linear,precision_linear,recall_linear,f1_linear])
t.add_row(['sigmoid',acc_sigmoid,precision_sigmoid,recall_sigmoid,f1_sigmoid])
t.add_row(['poly',acc_poly,precision_poly,recall_poly,f1_poly])
t.add_row(['rbf',acc_rbf,precision_rbf,recall_rbf,f1_rbf])
print(t)

--------------------
Confusion Matrix: 
 [[17  0  0]
 [ 0 12  2]
 [ 0  0 14]]
--------------------
Accuracy:  0.9555555555555556
--------------------
+---------+--------------------+--------------------+--------------------+--------------------+
|         |        acc         |     precision      |       recall       |         f1         |
+---------+--------------------+--------------------+--------------------+--------------------+
|  linear | 0.9555555555555556 | 0.9555555555555556 | 0.9555555555555556 | 0.9555555555555556 |
| sigmoid |       0.1556       |       0.1556       |       0.1556       |       0.1556       |
|   poly  |       0.9556       |       0.9556       |       0.9556       |       0.9556       |
|   rbf   |       0.9778       |       0.9778       |       0.9778       |       0.9778       |
+---------+--------------------+--------------------+--------------------+--------------------+


#Task 3. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with mnist dataset based on accuracy, precision, recall, f1 measures.


In [51]:
data_mnist = datasets.load_digits()
X = data_mnist.data
y = data_mnist.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_svm = metrics.accuracy_score(y_test, y_pred)
precision_svm = metrics.precision_score(y_test, y_pred, average='micro')
recall_svm = metrics.recall_score(y_test, y_pred, average='micro')
f1_svm = metrics.f1_score(y_test, y_pred, average='micro')

dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
acc_dtree = round((metrics.accuracy_score(y_test, y_pred)),4)
precision_dtree = round((metrics.precision_score(y_test, y_pred, average = 'macro')),4)
f1_dtree = round((metrics.f1_score(y_test, y_pred, average = 'macro')),4)
recall_dtree = round((metrics.recall_score(y_test, y_pred, average = 'macro')),4)

k_range = range(1, 30, 2)
accs = []
precision = []
recall = []
f1 = []
for k in k_range:
  KNN = KNeighborsClassifier(n_neighbors = k)
  KNN.fit(X_train, y_train)
  y_pred = KNN.predict(X_test)
  accs.append(metrics.accuracy_score(y_test, y_pred))
  precision.append(metrics.precision_score(y_test, y_pred, average = 'micro'))
  recall.append(metrics.recall_score(y_test, y_pred, average = 'micro'))
  f1.append(metrics.f1_score(y_test, y_pred, average = 'micro'))
acc_knn = round(max(accs),4)
precision_knn = round(max(precision),4)
f1_knn = round(max(f1),4)
recall_knn = round(max(recall),4)

classifier = LogisticRegression(random_state = 0, max_iter=10000)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
acc_logistic = round((metrics.accuracy_score(y_test, y_pred)),4)
precision_logistic = round((metrics.precision_score(y_test, y_pred, average = 'macro')),4)
f1_logistic = round((metrics.f1_score(y_test, y_pred, average = 'macro')),4)
recall_logistic = round((metrics.recall_score(y_test, y_pred, average = 'macro')),4)

t = PrettyTable(['','acc','precision','recall','f1'])
t.add_row(['kNN',acc_knn,precision_knn,recall_knn,f1_knn])
t.add_row(['Decision Tree',acc_dtree,precision_dtree,recall_dtree,f1_dtree])
t.add_row(['Logistic Regression',acc_logistic,precision_logistic,recall_logistic,f1_logistic])
t.add_row(['SVM',acc_svm,precision_svm,recall_svm,f1_svm])
print(t)

+---------------------+--------------------+--------------------+--------------------+--------------------+
|                     |        acc         |     precision      |       recall       |         f1         |
+---------------------+--------------------+--------------------+--------------------+--------------------+
|         kNN         |       0.9907       |       0.9907       |       0.9907       |       0.9907       |
|    Decision Tree    |       0.8407       |       0.8444       |       0.8416       |       0.8415       |
| Logistic Regression |       0.9685       |       0.9673       |       0.9681       |       0.9674       |
|         SVM         | 0.9851851851851852 | 0.9851851851851852 | 0.9851851851851852 | 0.9851851851851852 |
+---------------------+--------------------+--------------------+--------------------+--------------------+


#Task 4. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with **credit card dataset** based on accuracy, precision, recall, f1 measures.

*   Give some comments on the obtained results
*   Identify issues with dataset, and propose the solutions to these issues



In [43]:
# code
data_credit = pd.read_csv('creditcard.csv')
# data_credit.columns
X = data_credit[['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']]
y = data_credit[['Class']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [ ]:
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_svm = metrics.accuracy_score(y_test, y_pred)
precision_svm = metrics.precision_score(y_test, y_pred, average='micro')
recall_svm = metrics.recall_score(y_test, y_pred, average='micro')
f1_svm = metrics.f1_score(y_test, y_pred, average='micro')

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [50]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
acc_dtree = round((metrics.accuracy_score(y_test, y_pred)),4)
precision_dtree = round((metrics.precision_score(y_test, y_pred, average = 'macro')),4)
f1_dtree = round((metrics.f1_score(y_test, y_pred, average = 'macro')),4)
recall_dtree = round((metrics.recall_score(y_test, y_pred, average = 'macro')),4)

k_range = range(1, 30, 2)
accs = []
precision = []
recall = []
f1 = []
for k in k_range:
  KNN = KNeighborsClassifier(n_neighbors = k)
  KNN.fit(X_train, y_train)
  y_pred = KNN.predict(X_test)
  accs.append(metrics.accuracy_score(y_test, y_pred))
  precision.append(metrics.precision_score(y_test, y_pred, average = 'micro'))
  recall.append(metrics.recall_score(y_test, y_pred, average = 'micro'))
  f1.append(metrics.f1_score(y_test, y_pred, average = 'micro'))
acc_knn = round(max(accs),4)
precision_knn = round(max(precision),4)
f1_knn = round(max(f1),4)
recall_knn = round(max(recall),4)

classifier = LogisticRegression(random_state = 0, max_iter=10000)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
acc_logistic = round((metrics.accuracy_score(y_test, y_pred)),4)
precision_logistic = round((metrics.precision_score(y_test, y_pred, average = 'macro')),4)
f1_logistic = round((metrics.f1_score(y_test, y_pred, average = 'macro')),4)
recall_logistic = round((metrics.recall_score(y_test, y_pred, average = 'macro')),4)

t = PrettyTable(['','acc','precision','recall','f1'])
t.add_row(['kNN',acc_knn,precision_knn,recall_knn,f1_knn])
t.add_row(['Decision Tree',acc_dtree,precision_dtree,recall_dtree,f1_dtree])
t.add_row(['Logistic Regression',acc_logistic,precision_logistic,recall_logistic,f1_logistic])
t.add_row(['SVM',acc_svm,precision_svm,recall_svm,f1_svm])
print(t)

+---------------------+--------------------+--------------------+--------------------+--------------------+
|                     |        acc         |     precision      |       recall       |         f1         |
+---------------------+--------------------+--------------------+--------------------+--------------------+
|         kNN         |       0.9907       |       0.9907       |       0.9907       |       0.9907       |
|    Decision Tree    |       0.8593       |       0.8584       |       0.8599       |       0.858        |
| Logistic Regression |       0.9685       |       0.9673       |       0.9681       |       0.9674       |
|         SVM         | 0.9851851851851852 | 0.9851851851851852 | 0.9851851851851852 | 0.9851851851851852 |
+---------------------+--------------------+--------------------+--------------------+--------------------+


#Finally,
Save a copy in your Github. Remember renaming the notebook.